### ISSUE TITLE
[KeyError]: 'rev'

### ISSUE THREAD

**Issue by g0di** [GabDug/sync-pre-commit-lock#4]
Hello,

I'm facing an error when using this plugin as part of a PDM project. My `.pre-commit-config.yaml` looks like the following
```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.280"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args: [src, tests, --color-output]
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

```
Whenever the plugin is run, for example after running a PDM command `pdm add pydantic` I get the following output:
```bash
$ pdm add pydantic
Adding packages to default dependencies: pydantic
🔒 Lock successful
Changes are written to pyproject.toml.
[KeyError]: 'rev'
Add '-v' to see the detailed traceback
``` 

Following is the detailed traceback
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\TBEBGOD\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 157, in handle       
    command.handle(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\add.py", line 67, in handle
    self.do_add(
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\add.py", line 175, in do_add
    hooks.try_emit("post_lock", resolution=resolved, dry_run=dry_run)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\hooks.py", line 54, in try_emit 
    pdm_signals.signal(name).send(self.project, hooks=self, **kwargs)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\blinker\base.py", line 300, in send
    result = receiver(sender, **kwargs)  # type: ignore[call-arg]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\sync_pre_commit_lock\pdm_plugin.py", line 107, in on_pdm_lock_check_pre_commit
    action.execute()
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\sync_pre_commit_lock\actions\sync_hooks.py", line 127, in execute
    to_fix = self.analyze_repos(pre_commit_config_data.repos_normalized, mapping, mapping_reverse_by_url)                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\.pyenv\pyenv-win\versions\3.11.4\Lib\functools.py", line 1001, in __get__       
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\sync_pre_commit_lock\actions\sync_hooks.py", line 65, in repos_normalized
    return {PreCommitRepo(repo=normalize_git_url(repo.repo), rev=repo.rev) for repo in self.repos}       
                                                                                       ^^^^^^^^^^        
  File "C:\Users\TBEBGOD\.pyenv\pyenv-win\versions\3.11.4\Lib\functools.py", line 1001, in __get__       
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\sync_pre_commit_lock\actions\sync_hooks.py", line 61, in repos
    return [PreCommitRepo(repo=repo["repo"], rev=repo["rev"]) for repo in (self.data["repos"] or [])]    
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\sync_pre_commit_lock\actions\sync_hooks.py", line 61, in <listcomp>
    return [PreCommitRepo(repo=repo["repo"], rev=repo["rev"]) for repo in (self.data["repos"] or [])]    
                                                 ~~~~^^^^^^^
KeyError: 'rev'
```

As far as I understand this is caused by the `local` repo defined for using `mypy`. It looks like the tool always expect to find a `rev` key which is not supposed to be there for local repos.

Python version `3.11.4`
PDM version: `2.8.0`
sync-pre-commit-lock version: `0.1.2`

**Comment by GabDug** [comment]
Hello!
This is indeed caused by the local hooks, the plugin has currently a very naive approach.

I'm working on improvements, I'll make sure to add tests with local hooks and update this issue.

**Comment by GabDug** [comment]
Hey @g0di, 
it should be fixed in the latest release.

Let me know if you run into any issue (never tested on Windows for instance), or if you have somme feedback!

**Comment by g0di** [comment]
Working fine now, thanks a lot for your reactivity!
